language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cmeister2
  password:
    secure: FZtEKhFdUxLN0V8b9BobdEaF/5ER7dK2RVHsx9V7Pcf7fvmLG7z2P0zcMtWcATunITdEGdALb5qeJCr6m6uT8bKhfpjU0qQ45man3S/nwXnnLaV6zh1wPSgbI02el47dLxhVOihYnYXeT+6l/zqyV3qlUHI5kEUnSOZjGrPp2h5eh9KyhG7TajvJ/6OfRh0WMgc1QAcF3M8Sk14rNVIobg0MzJKssCEhDR7hCyPevoEBF+o8ADLvL77T4p+ZqiWx00YkcPKjdJKfpbdjGAgQi/JjwsvF516Kn6JcDMoucxBUcY6FrlaS+DMDLAmnmRcLIrms9htV2OpntxEgMcPJIahWYRBHx0TL3Su0VQMJ7/wvp3DEwBU2Bw0ECxATAUZqwYTg+l9WkgZrZizbHG64jDToah481uiPtRR9+BW6WSou4Ve3DeHSqTDiviS37p/GiYIpbw38EuCnAe3y7fdNC2jo6Nqnah4EwmtrziqzuRHZs0btZZn6ONiAmmCSVjXdIqBHOW65G7t1c3mAwO+Ubq7qle3c968ONbOhyUgdzyPxlicFskR/YwupMCIqNrSQrSgHTTSRCl+i4B4iNGMsUsHAuVCG7/xjR0+RyeRACAx4/KnZGXwE6w0hkvWrkNhJBq7edrrynqdPNS/cKL+5eJkiSbGXzQ57+oUBdx2n+DY=
  on:
    tags: true
    repo: cmeister2/requests_ratelimit_adapter
    python: 3.6
